import Head from 'next/head'
import { useSession, signOut } from "next-auth/react";
import LoginPage from '../components/LoginPage';

export default function Home() {

  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      {session ? (
        <>
          <h1>Werlcome, {session.user.name}</h1>
        </>
      ) : (
        <>
          <div className='flex justify-center items-center md:h-screen pt-5'>
            <LoginPage />
          </div>  
        </>
      )}

    </>
  )
}
